name: Deploy Flask Application to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy application over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e

            echo "Changing directory..."
            cd /home/ubuntu/Assesment-AWS-Infra

            echo "Pulling latest code..."
            git pull origin main

            echo "Entering application directory..."
            cd aws-assessment

            echo "Activating virtual environment..."
            source venv/bin/activate

            echo "Installing dependencies..."
            pip install -r requirements.txt

            echo "Restarting Gunicorn service..."
            sudo systemctl restart flaskapp

            echo "Checking service status..."
            sudo systemctl status flaskapp --no-pager

            echo "Deployment completed successfully."
